
import React from 'react';
import type { Subject } from './types';
import { MathIcon, LiteratureIcon, PhysicsIcon, EnglishIcon, BiologyIcon, HistoryIcon, ChemistryIcon, GeographyIcon, CivicsIcon, TechnologyIcon, InformaticsIcon, PEIcon, MusicIcon, ArtIcon, ActivitiesIcon, HomeroomIcon } from './components/icons';

export const DAYS_OF_WEEK = {
  en: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  vi: ["Thứ Hai", "Thứ Ba", "Thứ Tư", "Thứ Năm", "Thứ Sáu", "Thứ Bảy"],
};

export const TRANSLATIONS = {
  en: {
    today: "Today",
    timetable: "Timetable",
    settings: "Settings",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    language: "Language",
    english: "English",
    vietnamese: "Vietnamese",
    notifications: "Notifications",
    enabled: "Enabled",
    disabled: "Disabled",
    no_classes_today: "No classes today! 😊",
    no_classes_this_day: "No classes scheduled for this day.",
    add_subject: "Add Subject",
    edit_subject: "Edit Subject",
    subject_name: "Subject Name",
    day_of_week: "Day of the Week",
    start_time: "Start Time",
    end_time: "End Time",
    color: "Color",
    save: "Save",
    delete: "Delete",
    close: "Close",
    are_you_sure_delete: "Are you sure you want to delete this subject?",
    upcoming_classes: "Upcoming Classes",
    quote_of_the_day: "Quote of the day",
    morning: "Morning",
    afternoon: "Afternoon",
    period: "Period",
    period_times: "Period Times",
    title: "Title",
    teacher: "Teacher",
    room: "Room",
    notes: "Notes",
    tags: "Tags",
    weekView: "Week",
    timelineView: "Timeline",
    dayView: "Day",
    extrasView: "Extra Classes",
    noTeacher: "No teacher",
    noRoom: "No room",
    currentTime: "Current Time",
    quickNotes: "Quick Notes",
    addTag: "Add Tag",
    isExtraClass: "Extra Class",
    search: "Search",
    searchPlaceholder: "Search subjects, teachers...",
    filterBy: "Filter by",
    exportData: "Export",
    importData: "Import",
    noResults: "No results found",
    resultsFound: "results",
    clearSearch: "Clear search",
    exportJSON: "Export JSON",
    exportCSV: "Export CSV",
    dragDropFile: "Drag & drop file or click to browse",
    invalidFile: "Invalid file format",
    importSuccess: "Import successful!",
    download: "Download",
    addFirstSubject: "Add your first subject",
    importDataAction: "Import data",
    tryDifferentKeywords: "Try different keywords",
    // Phase 4 - Premium Features
    statistics: "Statistics",
    homework: "Homework",
    studyTimer: "Study Timer",
    totalHours: "Total Hours",
    sessionsToday: "Sessions Today",
    focusTime: "Focus Time",
    addHomework: "Add Homework",
    homeworkTitle: "Homework Title",
    dueDate: "Due Date",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    completed: "Completed",
    pending: "Pending",
    overdue: "Overdue",
    startTimer: "Start",
    pauseTimer: "Pause",
    stopTimer: "Stop",
    resetTimer: "Reset",
    workDuration: "Work Duration",
    breakDuration: "Break Duration",
    minutes: "minutes",
    enableNotifications: "Enable Notifications",
    notificationPermission: "Request Permission",
    classReminder: "Class Reminder",
    homeworkDue: "Homework Due Soon",
    dailySummary: "Daily Summary",
  },
  vi: {
    today: "Hôm nay",
    timetable: "Thời khóa biểu",
    settings: "Cài đặt",
    theme: "Giao diện",
    light: "Sáng",
    dark: "Tối",
    language: "Ngôn ngữ",
    english: "Tiếng Anh",
    vietnamese: "Tiếng Việt",
    notifications: "Thông báo",
    enabled: "Bật",
    disabled: "Tắt",
    no_classes_today: "Chưa có tiết học nào hôm nay 😊",
    no_classes_this_day: "Không có tiết học nào cho ngày này.",
    add_subject: "Thêm môn học",
    edit_subject: "Sửa môn học",
    subject_name: "Tên môn học",
    day_of_week: "Ngày trong tuần",
    start_time: "Giờ bắt đầu",
    end_time: "Giờ kết thúc",
    color: "Màu sắc",
    save: "Lưu",
    delete: "Xóa",
    close: "Đóng",
    are_you_sure_delete: "Bạn có chắc chắn muốn xóa môn học này?",
    upcoming_classes: "Các tiết học sắp tới",
    quote_of_the_day: "Châm ngôn mỗi ngày",
    morning: "Sáng",
    afternoon: "Chiều",
    period: "Tiết",
    period_times: "Thời gian tiết học",
    title: "Tiêu đề",
    teacher: "Giáo viên",
    room: "Phòng học",
    notes: "Ghi chú",
    tags: "Nhãn",
    weekView: "Tuần",
    timelineView: "Lịch",
    dayView: "Ngày",
    extrasView: "Học thêm",
    noTeacher: "Chưa có giáo viên",
    noRoom: "Chưa có phòng",
    currentTime: "Thời gian hiện tại",
    quickNotes: "Ghi chú nhanh",
    addTag: "Thêm nhãn",
    isExtraClass: "Học thêm",
    search: "Tìm kiếm",
    searchPlaceholder: "Tìm kiếm môn học, giáo viên...",
    filterBy: "Lọc theo",
    exportData: "Xuất dữ liệu",
    importData: "Nhập dữ liệu",
    noResults: "Không tìm thấy kết quả",
    resultsFound: "kết quả",
    clearSearch: "Xóa tìm kiếm",
    exportJSON: "Xuất JSON",
    exportCSV: "Xuất CSV",
    dragDropFile: "Kéo thả file hoặc click để chọn",
    invalidFile: "File không hợp lệ",
    importSuccess: "Import thành công!",
    download: "Tải xuống",
    addFirstSubject: "Thêm môn học đầu tiên",
    importDataAction: "Import dữ liệu",
    tryDifferentKeywords: "Thử từ khóa khác",
    // Phase 4 - Premium Features
    statistics: "Thống kê",
    homework: "Bài tập",
    studyTimer: "Đồng hồ học",
    totalHours: "Tổng giờ học",
    sessionsToday: "Phiên học hôm nay",
    focusTime: "Thời gian tập trung",
    addHomework: "Thêm bài tập",
    homeworkTitle: "Tiêu đề bài tập",
    dueDate: "Hạn nộp",
    priority: "Mức độ",
    high: "Cao",
    medium: "Trung bình",
    low: "Thấp",
    completed: "Hoàn thành",
    pending: "Đang làm",
    overdue: "Quá hạn",
    startTimer: "Bắt đầu",
    pauseTimer: "Tạm dừng",
    stopTimer: "Dừng",
    resetTimer: "Đặt lại",
    workDuration: "Thời gian làm việc",
    breakDuration: "Thời gian nghỉ",
    minutes: "phút",
    enableNotifications: "Bật thông báo",
    notificationPermission: "Yêu cầu quyền",
    classReminder: "Nhắc tiết học",
    homeworkDue: "Bài tập sắp hết hạn",
    dailySummary: "Tóm tắt hàng ngày",
  },
};

export const MOTIVATIONAL_QUOTES = {
  en: [
    "The secret of getting ahead is getting started.",
    "Believe you can and you’re halfway there.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts."
  ],
  vi: [
    "Bí mật của sự tiến bộ là hãy bắt đầu.",
    "Hãy tin rằng bạn có thể và bạn đã đi được nửa chặng đường.",
    "Tương lai thuộc về những người tin vào vẻ đẹp của những giấc mơ.",
    "Không quan trọng bạn đi chậm như thế nào, miễn là bạn không dừng lại.",
    "Thành công không phải là cuối cùng, thất bại không phải là chí mạng: lòng can đảm đi tiếp mới là quan trọng."
  ]
};

export const VIETNAM_GRADE_8_SUBJECTS = [
  'Toán',
  'Ngữ văn',
  'Tiếng Anh',
  'Giáo dục công dân',
  'Lịch sử & Địa lí',
  'Khoa học tự nhiên',
  'Công nghệ',
  'Tin học',
  'Thể dục',
  'Âm nhạc',
  'Mĩ thuật',
  'Hoạt động trải nghiệm',
  'Sinh hoạt lớp',
];

export const SUBJECT_ICONS: { [key: string]: React.FC<React.SVGProps<SVGSVGElement>> } = {
  'toán': MathIcon,
  'ngữ văn': LiteratureIcon,
  'văn': LiteratureIcon,
  'tiếng anh': EnglishIcon,
  'anh': EnglishIcon,
  'giáo dục công dân': CivicsIcon,
  'gdcd': CivicsIcon,
  'lịch sử & địa lí': HistoryIcon,
  'sử': HistoryIcon,
  'địa': GeographyIcon,
  'khoa học tự nhiên': ChemistryIcon,
  'khtn': ChemistryIcon,
  'lý': PhysicsIcon,
  'hóa': ChemistryIcon,
  'sinh': BiologyIcon,
  'công nghệ': TechnologyIcon,
  'tin học': InformaticsIcon,
  'thể dục': PEIcon,
  'âm nhạc': MusicIcon,
  'mĩ thuật': ArtIcon,
  'hoạt động trải nghiệm': ActivitiesIcon,
  'sinh hoạt lớp': HomeroomIcon,
  // English fallbacks
  'math': MathIcon,
  'literature': LiteratureIcon,
  'physics': PhysicsIcon,
  'english': EnglishIcon,
  'biology': BiologyIcon,
  'history': HistoryIcon,
  'chemistry': ChemistryIcon,
  'geography': GeographyIcon,
};


export const SUBJECT_COLORS = [
  '#fecaca', '#fed7aa', '#fef08a', '#d9f99d', '#bfdbfe', '#e9d5ff', '#fbcfe8', '#bae6fd'
];
export const SUBJECT_COLORS_DARK = [
  '#991b1b', '#9a3412', '#a16207', '#4d7c0f', '#1e40af', '#6b21a8', '#9d174d', '#0c4a6e'
];

export const DUMMY_SUBJECTS: Subject[] = [
  { id: '1', name: 'Toán', startTime: '07:15', endTime: '08:00', day: 0, color: '#fecaca' },
  { id: '2', name: 'Ngữ văn', startTime: '08:05', endTime: '08:50', day: 0, color: '#fed7aa' },
  { id: '3', name: 'Tiếng Anh', startTime: '09:00', endTime: '09:45', day: 0, color: '#d9f99d' },
  { id: '4', name: 'Khoa học tự nhiên', startTime: '07:15', endTime: '08:00', day: 1, color: '#bfdbfe' },
  { id: '5', name: 'Lịch sử & Địa lí', startTime: '08:05', endTime: '08:50', day: 1, color: '#e9d5ff' },
  { id: '6', name: 'Thể dục', startTime: '13:00', endTime: '13:45', day: 2, color: '#fbcfe8' },
  { id: '7', name: 'Tin học', startTime: '13:50', endTime: '14:35', day: 2, color: '#bae6fd' },
  { id: '8', name: 'Công nghệ', startTime: '07:15', endTime: '08:00', day: 3, color: '#fecaca'},
  { id: '9', name: 'Mĩ thuật', startTime: '13:00', endTime: '13:45', day: 4, color: '#d9f99d'},
  { id: '10', name: 'Sinh hoạt lớp', startTime: '10:40', endTime: '11:25', day: 5, color: '#e9d5ff' },
];

export const CLASS_PERIODS = {
  morning: [
    { period: 1, startTime: '07:15', endTime: '08:00' },
    { period: 2, startTime: '08:05', endTime: '08:50' },
    { period: 3, startTime: '09:00', endTime: '09:45' },
    { period: 4, startTime: '09:50', endTime: '10:35' },
    { period: 5, startTime: '10:40', endTime: '11:25' },
  ],
  afternoon: [
    { period: 1, startTime: '13:00', endTime: '13:45' },
    { period: 2, startTime: '13:50', endTime: '14:35' },
    { period: 3, startTime: '14:45', endTime: '15:30' },
    { period: 4, startTime: '15:35', endTime: '16:20' },
  ]
};
